# Generated by Django 2.2.5 on 2020-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(default=0, upload_to='Products'),
            preserve_default=False,
        ),
    ]
